### ISSUE TITLE
About the LoRA implement in the code.

### ISSUE THREAD

**Issue by xin-ran-w** [CircleRadon/Osprey#20]
HeIlo, I want to use LoRA to finetune the LlamaDecoder in Osprey on downstream tasks. There is a `lora_enable` in the training args, I set it to true but there is an error when I run stage 3 training. Is the Lora training option available here？

**Comment by xin-ran-w** [comment]
Here is the error information
```
Adding LoRA adapters...
Traceback (most recent call last):
  File "/home/wangxinran/Osprey/osprey/train/train_mem.py", line 13, in <module>
    train()
  File "/home/wangxinran/Osprey/osprey/train/train.py", line 625, in train
    model = get_peft_model(model, lora_config)
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/mapping.py", line 98, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/peft_model.py", line 893, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/peft_model.py", line 112, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter
    self._find_and_replace(adapter_name)
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target)
  File "/data/wangxinran/anaconda3/envs/osprey/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module
    raise ValueError(
ValueError: Target module LlamaDecoderLayer(
  (self_attn): LlamaAttention(
    (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
    (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
    (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
    (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (mlp): LlamaMLP(
    (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
    (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
    (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
    (act_fn): SiLUActivation()
  )
  (input_layernorm): LlamaRMSNorm()
  (post_attention_layernorm): LlamaRMSNorm()
) is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.
[2024-02-20 20:04:44,773] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1543537
```

**Comment by LiWentomng** [comment]
@xin-ran-w 
Thanks. We have not yet tested the LoRa. We plan to include this feature in coming updates.  We also  openly welcome the pull request (PR) for this feature.

**Comment by xin-ran-w** [comment]
Thanks for your reply, looking forward to your update.

**Comment by CharlesGong12** [comment]
@xin-ran-w @LiWentomng Hi, did you solve the LoRA implementation problem?

**Comment by Z-MU-Z** [comment]
+1

**Comment by yj772881654** [comment]
<img width="645" alt="Image" src="https://github.com/user-attachments/assets/54fe6328-17e3-4bc0-a5fd-177a7d67e38f" />

It seems can resolve this problem.
Modifying target_modules to "q_proj","v_proj” can enable LoRA. For specific target_modules configurations, you can refer to https://blog.csdn.net/u014297502/article/details/140998350. Use regular expressions to make the selection.
