### ISSUE TITLE
ERROR IN AT END.

### ISSUE THREAD

**Issue by prabin333** [CircleRadon/Osprey#9]
34s
!python /content/Osprey/demo/app.py --model sunshine-lwt/Osprey-7b
output
2024-01-14 16:21:15.919229: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-14 16:21:15.919294: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-14 16:21:15.919351: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-14 16:21:17.052157: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading checkpoint shards: 100% 2/2 [00:12<00:00,  6.40s/it]
Some weights of the model checkpoint at sunshine-lwt/Osprey-7b were not used when initializing OspreyLlamaForCausalLM: ['model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.1.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.22.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.13.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.0.blocks.1.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.3.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.16.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.3.blocks.1.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.23.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.5.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.15.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.4.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.9.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.14.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.21.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.0.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.3.blocks.0.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.17.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.18.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.20.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.11.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.24.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.10.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.25.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.3.blocks.2.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.0.blocks.2.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.1.blocks.0.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.19.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.8.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.7.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.0.blocks.0.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.6.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.2.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.26.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.1.blocks.1.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.12.weight', 'model.vision_tower.vision_tower.visual.trunk.stages.1.blocks.2.weight']
- This IS expected if you are initializing OspreyLlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing OspreyLlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of OspreyLlamaForCausalLM were not initialized from the model checkpoint at sunshine-lwt/Osprey-7b and are newly initialized: ['model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.20.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.19.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.3.blocks.2.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.10.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.7.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.1.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.23.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.22.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.15.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.1.blocks.1.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.17.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.3.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.0.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.18.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.8.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.14.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.13.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.1.blocks.2.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.16.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.25.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.6.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.24.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.0.blocks.2.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.2.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.9.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.26.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.0.blocks.0.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.3.blocks.0.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.0.blocks.1.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.4.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.5.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.21.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.11.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.2.blocks.12.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.1.blocks.0.gamma', 'model.vision_tower.vision_tower.visual.trunk.stages.3.blocks.1.gamma']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
Traceback (most recent call last):
  File "/content/Osprey/demo/app.py", line 20, in <module>
    sam_predictor = get_sam_predictor()
  File "/content/Osprey/demo/inference.py", line 15, in get_sam_predictor
    sam = sam_model_registry[model_type](checkpoint=models[model_type])
  File "/usr/local/lib/python3.10/dist-packages/segment_anything/build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
  File "/usr/local/lib/python3.10/dist-packages/segment_anything/build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/sam_vit_b_01ec64.pth'

**Comment by CircleRadon** [comment]
Hi, @prabin333 
you should  download [ViT-B SAM model](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth) to `./checkpoints`, 

or change this line to the path of ViT-B SAM model. https://github.com/CircleRadon/Osprey/blob/ce786ba5f612de3166039c4a9c196f77352f702c/demo/inference.py#L8

**Comment by prabin333** [comment]
I'm currently using Google Colab. Could you please guide me on where to put the checkpoints folder and other required folders? I have already downloaded the Vit-B, SAM, and CLIP models, and placed them inside the checkpoints folder.


2024-01-18 05:23:43.070875: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-18 05:23:43.070933: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-18 05:23:43.073035: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-18 05:23:44.112812: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/Osprey/demo/app.py", line 19, in <module>
    osprey_ = Osprey(model_path=args.model)
  File "/content/Osprey/demo/osprey_inference.py", line 43, in __init__
    self.model = OspreyLlamaForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3462, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/osprey/model/language_model/osprey_llama.py", line 45, in __init__
    self.model = OspreyLlamaModel(config)
  File "/usr/local/lib/python3.10/dist-packages/osprey/model/language_model/osprey_llama.py", line 37, in __init__
    super(OspreyLlamaModel, self).__init__(config)
  File "/usr/local/lib/python3.10/dist-packages/osprey/model/osprey_arch.py", line 31, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=False)
  File "/usr/local/lib/python3.10/dist-packages/osprey/model/multimodal_encoder/builder.py", line 7, in build_vision_tower
    return CLIPVisionTower(args=vision_tower_cfg)
  File "/usr/local/lib/python3.10/dist-packages/osprey/model/multimodal_encoder/clip_encoder.py", line 20, in __init__
    self.load_model()
  File "/usr/local/lib/python3.10/dist-packages/osprey/model/multimodal_encoder/clip_encoder.py", line 29, in load_model
    self.vision_tower.load_state_dict(torch.load(self.clip_model),strict=False)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'open_clip_pytorch_model.bin'

**Comment by CircleRadon** [comment]
It appears that the path to the CLIP model is incorrect. Based on the error message and the location of your checkpoints, please update [this line](https://huggingface.co/sunshine-lwt/Osprey-7b/blob/50b6ac5e27319ee93ce60c9d33ae1f32d17423bc/config.json#L19) in the config.json file of Osprey-7b model to reflect the correct path for the CLIP model, i.e., `./checkpoints/open_clip_pytorch_model.bin`.

**Comment by CircleRadon** [comment]
In colab, localhost is not accessible, you can set `os.environ["no_proxy"] = "localhost,127.0.0.1,::1”` in colab. I tried it and it works.
![Pasted Graphic](https://github.com/CircleRadon/Osprey/assets/61010385/7babfff0-efe7-4d20-9388-09eef860aa4a)

**Comment by prabin333** [comment]
import os
os.environ["no_proxy"] = "localhost,127.0.0.1,::1"


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Osprey/demo/app.py", line 5, in <module>
    import gradio as gr
  File "/content/gradio-osprey-demo/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/content/gradio-osprey-demo/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/content/gradio-osprey-demo/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/content/gradio-osprey-demo/gradio/utils.py", line 346, in <module>
    class AsyncRequest:
  File "/content/gradio-osprey-demo/gradio/utils.py", line 365, in AsyncRequest
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/usr/local/lib/python3.10/dist-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port
